package com.stack.api.entity;

import java.util.Date;

public class AccountFactory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_factory.account_factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer accountFactoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_factory.account_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_factory.factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_factory.note
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_factory.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_factory.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_factory.account_factory_id
     *
     * @return the value of account_factory.account_factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getAccountFactoryId() {
        return accountFactoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_factory.account_factory_id
     *
     * @param accountFactoryId the value for account_factory.account_factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAccountFactoryId(Integer accountFactoryId) {
        this.accountFactoryId = accountFactoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_factory.account_id
     *
     * @return the value of account_factory.account_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_factory.account_id
     *
     * @param accountId the value for account_factory.account_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_factory.factory_id
     *
     * @return the value of account_factory.factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_factory.factory_id
     *
     * @param factoryId the value for account_factory.factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_factory.note
     *
     * @return the value of account_factory.note
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_factory.note
     *
     * @param note the value for account_factory.note
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_factory.create_time
     *
     * @return the value of account_factory.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_factory.create_time
     *
     * @param createTime the value for account_factory.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_factory.update_time
     *
     * @return the value of account_factory.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_factory.update_time
     *
     * @param updateTime the value for account_factory.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}