package com.stack.api.entity;

import java.util.Date;

public class AccountGrid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_grid.account_grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer accountGridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_grid.account_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_grid.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_grid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_grid.account_grid_id
     *
     * @return the value of account_grid.account_grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getAccountGridId() {
        return accountGridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_grid.account_grid_id
     *
     * @param accountGridId the value for account_grid.account_grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAccountGridId(Integer accountGridId) {
        this.accountGridId = accountGridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_grid.account_id
     *
     * @return the value of account_grid.account_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_grid.account_id
     *
     * @param accountId the value for account_grid.account_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_grid.grid_id
     *
     * @return the value of account_grid.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_grid.grid_id
     *
     * @param gridId the value for account_grid.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_grid.create_time
     *
     * @return the value of account_grid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_grid.create_time
     *
     * @param createTime the value for account_grid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}