package com.stack.api.entity;

import java.util.Date;

public class DeviceDynamic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.status
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.alarm_confirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer alarmConfirmedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.alarm_unconfirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer alarmUnconfirmedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.last_alarm_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date lastAlarmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.fault_confirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer faultConfirmedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.fault_unconfirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer faultUnconfirmedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.last_fault_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date lastFaultTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dynamic.last_uptime
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date lastUptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.device_id
     *
     * @return the value of device_dynamic.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.device_id
     *
     * @param deviceId the value for device_dynamic.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.status
     *
     * @return the value of device_dynamic.status
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.status
     *
     * @param status the value for device_dynamic.status
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.alarm_confirmed_count
     *
     * @return the value of device_dynamic.alarm_confirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getAlarmConfirmedCount() {
        return alarmConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.alarm_confirmed_count
     *
     * @param alarmConfirmedCount the value for device_dynamic.alarm_confirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAlarmConfirmedCount(Integer alarmConfirmedCount) {
        this.alarmConfirmedCount = alarmConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.alarm_unconfirmed_count
     *
     * @return the value of device_dynamic.alarm_unconfirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getAlarmUnconfirmedCount() {
        return alarmUnconfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.alarm_unconfirmed_count
     *
     * @param alarmUnconfirmedCount the value for device_dynamic.alarm_unconfirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAlarmUnconfirmedCount(Integer alarmUnconfirmedCount) {
        this.alarmUnconfirmedCount = alarmUnconfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.last_alarm_time
     *
     * @return the value of device_dynamic.last_alarm_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getLastAlarmTime() {
        return lastAlarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.last_alarm_time
     *
     * @param lastAlarmTime the value for device_dynamic.last_alarm_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLastAlarmTime(Date lastAlarmTime) {
        this.lastAlarmTime = lastAlarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.fault_confirmed_count
     *
     * @return the value of device_dynamic.fault_confirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getFaultConfirmedCount() {
        return faultConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.fault_confirmed_count
     *
     * @param faultConfirmedCount the value for device_dynamic.fault_confirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setFaultConfirmedCount(Integer faultConfirmedCount) {
        this.faultConfirmedCount = faultConfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.fault_unconfirmed_count
     *
     * @return the value of device_dynamic.fault_unconfirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getFaultUnconfirmedCount() {
        return faultUnconfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.fault_unconfirmed_count
     *
     * @param faultUnconfirmedCount the value for device_dynamic.fault_unconfirmed_count
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setFaultUnconfirmedCount(Integer faultUnconfirmedCount) {
        this.faultUnconfirmedCount = faultUnconfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.last_fault_time
     *
     * @return the value of device_dynamic.last_fault_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getLastFaultTime() {
        return lastFaultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.last_fault_time
     *
     * @param lastFaultTime the value for device_dynamic.last_fault_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLastFaultTime(Date lastFaultTime) {
        this.lastFaultTime = lastFaultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dynamic.last_uptime
     *
     * @return the value of device_dynamic.last_uptime
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getLastUptime() {
        return lastUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dynamic.last_uptime
     *
     * @param lastUptime the value for device_dynamic.last_uptime
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLastUptime(Date lastUptime) {
        this.lastUptime = lastUptime;
    }
}