package com.stack.api.entity;

import java.util.Date;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.serial
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.type
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.model
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.province
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.city
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.district
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.address
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.longitude
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.latitude
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.plant_name
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String plantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.serial
     *
     * @return the value of device.serial
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.serial
     *
     * @param serial the value for device.serial
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.type
     *
     * @return the value of device.type
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.type
     *
     * @param type the value for device.type
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.model
     *
     * @return the value of device.model
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.model
     *
     * @param model the value for device.model
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.province
     *
     * @return the value of device.province
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.province
     *
     * @param province the value for device.province
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.city
     *
     * @return the value of device.city
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.city
     *
     * @param city the value for device.city
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.district
     *
     * @return the value of device.district
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.district
     *
     * @param district the value for device.district
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.address
     *
     * @return the value of device.address
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.address
     *
     * @param address the value for device.address
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.grid_id
     *
     * @return the value of device.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.grid_id
     *
     * @param gridId the value for device.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.longitude
     *
     * @return the value of device.longitude
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.longitude
     *
     * @param longitude the value for device.longitude
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.latitude
     *
     * @return the value of device.latitude
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.latitude
     *
     * @param latitude the value for device.latitude
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.factory_id
     *
     * @return the value of device.factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.factory_id
     *
     * @param factoryId the value for device.factory_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.plant_name
     *
     * @return the value of device.plant_name
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getPlantName() {
        return plantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.plant_name
     *
     * @param plantName the value for device.plant_name
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setPlantName(String plantName) {
        this.plantName = plantName == null ? null : plantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.create_time
     *
     * @return the value of device.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.create_time
     *
     * @param createTime the value for device.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.update_time
     *
     * @return the value of device.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.update_time
     *
     * @param updateTime the value for device.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}