package com.stack.api.entity;

import java.util.Date;

public class DryTemperature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dry_temperature.id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dry_temperature.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dry_temperature.temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dry_temperature.alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Byte alarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dry_temperature.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dry_temperature.id
     *
     * @return the value of dry_temperature.id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dry_temperature.id
     *
     * @param id the value for dry_temperature.id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dry_temperature.device_id
     *
     * @return the value of dry_temperature.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dry_temperature.device_id
     *
     * @param deviceId the value for dry_temperature.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dry_temperature.temperature
     *
     * @return the value of dry_temperature.temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dry_temperature.temperature
     *
     * @param temperature the value for dry_temperature.temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setTemperature(Short temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dry_temperature.alarm
     *
     * @return the value of dry_temperature.alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Byte getAlarm() {
        return alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dry_temperature.alarm
     *
     * @param alarm the value for dry_temperature.alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAlarm(Byte alarm) {
        this.alarm = alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dry_temperature.create_time
     *
     * @return the value of dry_temperature.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dry_temperature.create_time
     *
     * @param createTime the value for dry_temperature.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}