package com.stack.api.entity;

import java.util.Date;

public class Grid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.parent_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.name
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.level
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.note
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.grid_id
     *
     * @return the value of grid.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.grid_id
     *
     * @param gridId the value for grid.grid_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.parent_id
     *
     * @return the value of grid.parent_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.parent_id
     *
     * @param parentId the value for grid.parent_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.name
     *
     * @return the value of grid.name
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.name
     *
     * @param name the value for grid.name
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.level
     *
     * @return the value of grid.level
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.level
     *
     * @param level the value for grid.level
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.note
     *
     * @return the value of grid.note
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.note
     *
     * @param note the value for grid.note
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.update_time
     *
     * @return the value of grid.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.update_time
     *
     * @param updateTime the value for grid.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid.create_time
     *
     * @return the value of grid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid.create_time
     *
     * @param createTime the value for grid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}