package com.stack.api.entity;

import java.util.Date;

public class WetLiquid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_liquid.id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_liquid.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_liquid.liquid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short liquid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_liquid.alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Byte alarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_liquid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_liquid.id
     *
     * @return the value of wet_liquid.id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_liquid.id
     *
     * @param id the value for wet_liquid.id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_liquid.device_id
     *
     * @return the value of wet_liquid.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_liquid.device_id
     *
     * @param deviceId the value for wet_liquid.device_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_liquid.liquid
     *
     * @return the value of wet_liquid.liquid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getLiquid() {
        return liquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_liquid.liquid
     *
     * @param liquid the value for wet_liquid.liquid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLiquid(Short liquid) {
        this.liquid = liquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_liquid.alarm
     *
     * @return the value of wet_liquid.alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Byte getAlarm() {
        return alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_liquid.alarm
     *
     * @param alarm the value for wet_liquid.alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setAlarm(Byte alarm) {
        this.alarm = alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_liquid.create_time
     *
     * @return the value of wet_liquid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_liquid.create_time
     *
     * @param createTime the value for wet_liquid.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}