package com.stack.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WetThresholdExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public WetThresholdExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWetThresholdIdIsNull() {
            addCriterion("wet_threshold_id is null");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdIsNotNull() {
            addCriterion("wet_threshold_id is not null");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdEqualTo(Integer value) {
            addCriterion("wet_threshold_id =", value, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdNotEqualTo(Integer value) {
            addCriterion("wet_threshold_id <>", value, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdGreaterThan(Integer value) {
            addCriterion("wet_threshold_id >", value, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wet_threshold_id >=", value, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdLessThan(Integer value) {
            addCriterion("wet_threshold_id <", value, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdLessThanOrEqualTo(Integer value) {
            addCriterion("wet_threshold_id <=", value, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdIn(List<Integer> values) {
            addCriterion("wet_threshold_id in", values, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdNotIn(List<Integer> values) {
            addCriterion("wet_threshold_id not in", values, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdBetween(Integer value1, Integer value2) {
            addCriterion("wet_threshold_id between", value1, value2, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andWetThresholdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wet_threshold_id not between", value1, value2, "wetThresholdId");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("model is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("model is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("model =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("model <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("model >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("model >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("model <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("model <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("model like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("model not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("model in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("model not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("model between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("model not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andInOutPressureIsNull() {
            addCriterion("in_out_pressure is null");
            return (Criteria) this;
        }

        public Criteria andInOutPressureIsNotNull() {
            addCriterion("in_out_pressure is not null");
            return (Criteria) this;
        }

        public Criteria andInOutPressureEqualTo(Short value) {
            addCriterion("in_out_pressure =", value, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureNotEqualTo(Short value) {
            addCriterion("in_out_pressure <>", value, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureGreaterThan(Short value) {
            addCriterion("in_out_pressure >", value, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureGreaterThanOrEqualTo(Short value) {
            addCriterion("in_out_pressure >=", value, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureLessThan(Short value) {
            addCriterion("in_out_pressure <", value, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureLessThanOrEqualTo(Short value) {
            addCriterion("in_out_pressure <=", value, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureIn(List<Short> values) {
            addCriterion("in_out_pressure in", values, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureNotIn(List<Short> values) {
            addCriterion("in_out_pressure not in", values, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureBetween(Short value1, Short value2) {
            addCriterion("in_out_pressure between", value1, value2, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andInOutPressureNotBetween(Short value1, Short value2) {
            addCriterion("in_out_pressure not between", value1, value2, "inOutPressure");
            return (Criteria) this;
        }

        public Criteria andLiquidIsNull() {
            addCriterion("liquid is null");
            return (Criteria) this;
        }

        public Criteria andLiquidIsNotNull() {
            addCriterion("liquid is not null");
            return (Criteria) this;
        }

        public Criteria andLiquidEqualTo(Short value) {
            addCriterion("liquid =", value, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidNotEqualTo(Short value) {
            addCriterion("liquid <>", value, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidGreaterThan(Short value) {
            addCriterion("liquid >", value, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidGreaterThanOrEqualTo(Short value) {
            addCriterion("liquid >=", value, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidLessThan(Short value) {
            addCriterion("liquid <", value, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidLessThanOrEqualTo(Short value) {
            addCriterion("liquid <=", value, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidIn(List<Short> values) {
            addCriterion("liquid in", values, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidNotIn(List<Short> values) {
            addCriterion("liquid not in", values, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidBetween(Short value1, Short value2) {
            addCriterion("liquid between", value1, value2, "liquid");
            return (Criteria) this;
        }

        public Criteria andLiquidNotBetween(Short value1, Short value2) {
            addCriterion("liquid not between", value1, value2, "liquid");
            return (Criteria) this;
        }

        public Criteria andDustIsNull() {
            addCriterion("dust is null");
            return (Criteria) this;
        }

        public Criteria andDustIsNotNull() {
            addCriterion("dust is not null");
            return (Criteria) this;
        }

        public Criteria andDustEqualTo(Short value) {
            addCriterion("dust =", value, "dust");
            return (Criteria) this;
        }

        public Criteria andDustNotEqualTo(Short value) {
            addCriterion("dust <>", value, "dust");
            return (Criteria) this;
        }

        public Criteria andDustGreaterThan(Short value) {
            addCriterion("dust >", value, "dust");
            return (Criteria) this;
        }

        public Criteria andDustGreaterThanOrEqualTo(Short value) {
            addCriterion("dust >=", value, "dust");
            return (Criteria) this;
        }

        public Criteria andDustLessThan(Short value) {
            addCriterion("dust <", value, "dust");
            return (Criteria) this;
        }

        public Criteria andDustLessThanOrEqualTo(Short value) {
            addCriterion("dust <=", value, "dust");
            return (Criteria) this;
        }

        public Criteria andDustIn(List<Short> values) {
            addCriterion("dust in", values, "dust");
            return (Criteria) this;
        }

        public Criteria andDustNotIn(List<Short> values) {
            addCriterion("dust not in", values, "dust");
            return (Criteria) this;
        }

        public Criteria andDustBetween(Short value1, Short value2) {
            addCriterion("dust between", value1, value2, "dust");
            return (Criteria) this;
        }

        public Criteria andDustNotBetween(Short value1, Short value2) {
            addCriterion("dust not between", value1, value2, "dust");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureIsNull() {
            addCriterion("hydraulic_pressure is null");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureIsNotNull() {
            addCriterion("hydraulic_pressure is not null");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureEqualTo(Short value) {
            addCriterion("hydraulic_pressure =", value, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureNotEqualTo(Short value) {
            addCriterion("hydraulic_pressure <>", value, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureGreaterThan(Short value) {
            addCriterion("hydraulic_pressure >", value, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureGreaterThanOrEqualTo(Short value) {
            addCriterion("hydraulic_pressure >=", value, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureLessThan(Short value) {
            addCriterion("hydraulic_pressure <", value, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureLessThanOrEqualTo(Short value) {
            addCriterion("hydraulic_pressure <=", value, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureIn(List<Short> values) {
            addCriterion("hydraulic_pressure in", values, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureNotIn(List<Short> values) {
            addCriterion("hydraulic_pressure not in", values, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureBetween(Short value1, Short value2) {
            addCriterion("hydraulic_pressure between", value1, value2, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydraulicPressureNotBetween(Short value1, Short value2) {
            addCriterion("hydraulic_pressure not between", value1, value2, "hydraulicPressure");
            return (Criteria) this;
        }

        public Criteria andHydrogenIsNull() {
            addCriterion("hydrogen is null");
            return (Criteria) this;
        }

        public Criteria andHydrogenIsNotNull() {
            addCriterion("hydrogen is not null");
            return (Criteria) this;
        }

        public Criteria andHydrogenEqualTo(Short value) {
            addCriterion("hydrogen =", value, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenNotEqualTo(Short value) {
            addCriterion("hydrogen <>", value, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenGreaterThan(Short value) {
            addCriterion("hydrogen >", value, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenGreaterThanOrEqualTo(Short value) {
            addCriterion("hydrogen >=", value, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenLessThan(Short value) {
            addCriterion("hydrogen <", value, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenLessThanOrEqualTo(Short value) {
            addCriterion("hydrogen <=", value, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenIn(List<Short> values) {
            addCriterion("hydrogen in", values, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenNotIn(List<Short> values) {
            addCriterion("hydrogen not in", values, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenBetween(Short value1, Short value2) {
            addCriterion("hydrogen between", value1, value2, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andHydrogenNotBetween(Short value1, Short value2) {
            addCriterion("hydrogen not between", value1, value2, "hydrogen");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wet_threshold
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 20 10:58:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}