package com.stack.api.entity;

import java.util.Date;

public class WetThreshold {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.wet_threshold_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Integer wetThresholdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.model
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short inOutPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.liquid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short liquid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.dust
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short dust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.hydraulic_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short hydraulicPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.hydrogen
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Short hydrogen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wet_threshold.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.wet_threshold_id
     *
     * @return the value of wet_threshold.wet_threshold_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Integer getWetThresholdId() {
        return wetThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.wet_threshold_id
     *
     * @param wetThresholdId the value for wet_threshold.wet_threshold_id
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setWetThresholdId(Integer wetThresholdId) {
        this.wetThresholdId = wetThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.model
     *
     * @return the value of wet_threshold.model
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.model
     *
     * @param model the value for wet_threshold.model
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.in_out_pressure
     *
     * @return the value of wet_threshold.in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getInOutPressure() {
        return inOutPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.in_out_pressure
     *
     * @param inOutPressure the value for wet_threshold.in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setInOutPressure(Short inOutPressure) {
        this.inOutPressure = inOutPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.liquid
     *
     * @return the value of wet_threshold.liquid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getLiquid() {
        return liquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.liquid
     *
     * @param liquid the value for wet_threshold.liquid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setLiquid(Short liquid) {
        this.liquid = liquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.dust
     *
     * @return the value of wet_threshold.dust
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getDust() {
        return dust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.dust
     *
     * @param dust the value for wet_threshold.dust
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setDust(Short dust) {
        this.dust = dust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.hydraulic_pressure
     *
     * @return the value of wet_threshold.hydraulic_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getHydraulicPressure() {
        return hydraulicPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.hydraulic_pressure
     *
     * @param hydraulicPressure the value for wet_threshold.hydraulic_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setHydraulicPressure(Short hydraulicPressure) {
        this.hydraulicPressure = hydraulicPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.hydrogen
     *
     * @return the value of wet_threshold.hydrogen
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Short getHydrogen() {
        return hydrogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.hydrogen
     *
     * @param hydrogen the value for wet_threshold.hydrogen
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setHydrogen(Short hydrogen) {
        this.hydrogen = hydrogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.create_time
     *
     * @return the value of wet_threshold.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.create_time
     *
     * @param createTime the value for wet_threshold.create_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wet_threshold.update_time
     *
     * @return the value of wet_threshold.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wet_threshold.update_time
     *
     * @param updateTime the value for wet_threshold.update_time
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}