package com.stack.api.mapper;

import com.stack.api.entity.AccountFactory;
import com.stack.api.entity.AccountFactoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountFactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(AccountFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(AccountFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer accountFactoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(AccountFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(AccountFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<AccountFactory> selectByExample(AccountFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    AccountFactory selectByPrimaryKey(Integer accountFactoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountFactory record, @Param("example") AccountFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") AccountFactory record, @Param("example") AccountFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(AccountFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_factory
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(AccountFactory record);
}