package com.stack.api.mapper;

import com.stack.api.entity.AccountGrid;
import com.stack.api.entity.AccountGridExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountGridMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(AccountGridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(AccountGridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer accountGridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(AccountGrid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(AccountGrid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<AccountGrid> selectByExample(AccountGridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    AccountGrid selectByPrimaryKey(Integer accountGridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountGrid record, @Param("example") AccountGridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") AccountGrid record, @Param("example") AccountGridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(AccountGrid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(AccountGrid record);
}