package com.stack.api.mapper;

import com.stack.api.entity.AccountRole;
import com.stack.api.entity.AccountRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer roleAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<AccountRole> selectByExample(AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    AccountRole selectByPrimaryKey(Integer roleAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountRole record, @Param("example") AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") AccountRole record, @Param("example") AccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(AccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(AccountRole record);
}