package com.stack.api.mapper;

import com.stack.api.entity.Alarm;
import com.stack.api.entity.AlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer alarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<Alarm> selectByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    Alarm selectByPrimaryKey(Integer alarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(Alarm record);
}