package com.stack.api.mapper;

import com.stack.api.entity.DryAshPressure;
import com.stack.api.entity.DryAshPressureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DryAshPressureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(DryAshPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(DryAshPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(DryAshPressure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(DryAshPressure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<DryAshPressure> selectByExample(DryAshPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    DryAshPressure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") DryAshPressure record, @Param("example") DryAshPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") DryAshPressure record, @Param("example") DryAshPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(DryAshPressure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_ash_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(DryAshPressure record);
}