package com.stack.api.mapper;

import com.stack.api.entity.DryTemperature;
import com.stack.api.entity.DryTemperatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DryTemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(DryTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(DryTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(DryTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(DryTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<DryTemperature> selectByExample(DryTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    DryTemperature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") DryTemperature record, @Param("example") DryTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") DryTemperature record, @Param("example") DryTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(DryTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_temperature
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(DryTemperature record);
}