package com.stack.api.mapper;

import com.stack.api.entity.DryThreshold;
import com.stack.api.entity.DryThresholdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DryThresholdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(DryThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(DryThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer dryThresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(DryThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(DryThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<DryThreshold> selectByExample(DryThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    DryThreshold selectByPrimaryKey(Integer dryThresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") DryThreshold record, @Param("example") DryThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") DryThreshold record, @Param("example") DryThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(DryThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dry_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(DryThreshold record);
}