package com.stack.api.mapper;

import com.stack.api.entity.Grid;
import com.stack.api.entity.GridExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GridMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(GridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(GridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer gridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(Grid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(Grid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<Grid> selectByExample(GridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    Grid selectByPrimaryKey(Integer gridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") Grid record, @Param("example") GridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") Grid record, @Param("example") GridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(Grid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(Grid record);
}