package com.stack.api.mapper;

import com.stack.api.entity.WetInOutPressure;
import com.stack.api.entity.WetInOutPressureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WetInOutPressureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(WetInOutPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(WetInOutPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(WetInOutPressure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(WetInOutPressure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<WetInOutPressure> selectByExample(WetInOutPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    WetInOutPressure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") WetInOutPressure record, @Param("example") WetInOutPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") WetInOutPressure record, @Param("example") WetInOutPressureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(WetInOutPressure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_in_out_pressure
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(WetInOutPressure record);
}