package com.stack.api.mapper;

import com.stack.api.entity.WetThreshold;
import com.stack.api.entity.WetThresholdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WetThresholdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    long countByExample(WetThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByExample(WetThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int deleteByPrimaryKey(Integer wetThresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insert(WetThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int insertSelective(WetThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    List<WetThreshold> selectByExample(WetThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    WetThreshold selectByPrimaryKey(Integer wetThresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") WetThreshold record, @Param("example") WetThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByExample(@Param("record") WetThreshold record, @Param("example") WetThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKeySelective(WetThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wet_threshold
     *
     * @mbg.generated Thu Aug 20 10:58:15 CST 2020
     */
    int updateByPrimaryKey(WetThreshold record);
}